version: '3'
services:
  web:
    build: ./docker
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html/
      - ./docker/config/log/:/var/log/
    networks:|
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridgcmd
    ipam:
      config:
        - subnet: 10.5.0.0/16
